# Generated by Django 5.0.2 on 2024-02-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('slideName', models.CharField(max_length=50, verbose_name='슬라이더 이름')),
                ('assignToPage', models.CharField(max_length=50, verbose_name='할당된 페이지')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='slides/', verbose_name='이미지')),
                ('sloganHeading', models.CharField(max_length=100, verbose_name='올릴 내용')),
                ('caption', models.CharField(max_length=100, verbose_name='올릴 내용')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('link', models.URLField(blank=True, verbose_name='링크')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('isActive', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='업데이트 날짜')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPage.slider', verbose_name='소속 슬라이더')),
            ],
        ),
    ]
