# Generated by Django 5.0.2 on 2024-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='updatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='수정 날짜'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 날짜'),
        ),
    ]
