# Generated by Django 5.0.2 on 2024-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0002_slider_updateddate_alter_slide_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='assignToPage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='할당된 페이지'),
        ),
    ]
