# Generated by Django 5.0.2 on 2024-02-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0005_alter_slide_updateddate_alter_slider_updateddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textAlign', models.CharField(default='center', max_length=50, verbose_name='텍스트 정렬')),
                ('textSize', models.IntegerField(default=11, verbose_name='텍스트 크기')),
                ('textColor', models.CharField(default='black', max_length=20, verbose_name='텍스트 색상')),
                ('imageHeight', models.IntegerField(default=500, verbose_name='이미지 높이')),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='adminPage.slide')),
            ],
        ),
    ]
