# Generated by Django 5.0.2 on 2024-02-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0006_slidedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='링크'),
        ),
    ]
